Added tests for Storage + CI test run

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -12,6 +12,8 @@ env:
   mrtkProjectFilePath: submodules/MRTK/Source/Evergine.MRTK/Evergine.MRTK.csproj
   windowsSdkVersion: 18362
   buildConfiguration: Release
+  testResultsDirectory: testResults
+  testConfigurationCore: src/Xrv.Core.Tests/appsettings.json
 jobs:
   build:
     runs-on: windows-latest
@@ -50,6 +52,29 @@ jobs:
             nuget restore $_.FullName
             msbuild $_.FullName /p:Configuration=${{  env.buildConfiguration  }}
           }
+      - name: Prepare tests
+        shell: pwsh
+        run: |
+          Write-Host "Replace appsettings.json file for core tests"
+          (Invoke-WebRequest -URI "${{ secrets.XRV_CORE_TEST_SETTINGS_URL }}").Content > ${{  env.testConfigurationCore }}
+      - name: Run tests
+        shell: pwsh
+        run: |
+          Get-ChildItem -Path src -Recurse -Filter '*.Tests.csproj' | 
+          Foreach-Object { 
+            Write-Host "Running tests for $($_.Name)" 
+            dotnet test $_.FullName --configuration ${{  env.buildConfiguration  }} --logger trx --results-directory ${{  env.testResultsDirectory  }}
+          }
+          Write-Host "Collected test result files"
+          Get-ChildItem -Path ${{  env.testResultsDirectory  }} | Select FullName
+      - name: Publish test results
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test results
+          path: ${{  env.testResultsDirectory  }}/*.trx    # Path to test results
+          reporter: dotnet-trx
+        
         
       
       
